name: ActivityTracker
version: 0.5-alpha-2
main: dansplugins.activitytracker.ActivityTracker
api-version: 1.13

commands:
  activitytracker:
  at:

permissions:
  at.help:
    default: true
  at.info:
    default: true
  at.top:
    default: true