name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
          
    - name: Install stub dependencies for testing
      run: |
        # Create minimal stub JARs for external dependencies
        mkdir -p ~/.m2/repository/org/spigotmc/spigot-api/1.13-R0.1-SNAPSHOT
        mkdir -p ~/.m2/repository/com/github/Preponderous-Software/ponder/1.1
        
        # Create POMs and empty JARs
        cat > ~/.m2/repository/org/spigotmc/spigot-api/1.13-R0.1-SNAPSHOT/spigot-api-1.13-R0.1-SNAPSHOT.pom << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.13-R0.1-SNAPSHOT</version>
            <packaging>jar</packaging>
        </project>
        EOF
        
        cat > ~/.m2/repository/com/github/Preponderous-Software/ponder/1.1/ponder-1.1.pom << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.github.Preponderous-Software</groupId>
            <artifactId>ponder</artifactId>
            <version>1.1</version>
            <packaging>jar</packaging>
        </project>
        EOF
        
        # Create empty JAR files
        echo "UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==" | base64 -d > ~/.m2/repository/org/spigotmc/spigot-api/1.13-R0.1-SNAPSHOT/spigot-api-1.13-R0.1-SNAPSHOT.jar
        echo "UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==" | base64 -d > ~/.m2/repository/com/github/Preponderous-Software/ponder/1.1/ponder-1.1.jar
          
    - name: Compile code
      run: mvn clean compile --batch-mode -DskipTests=true
      
    - name: Run tests with coverage
      run: mvn test jacoco:report --batch-mode --offline -Dmaven.test.failure.ignore=true
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false